### ISSUE TITLE
Firmware request

### ISSUE THREAD

**Issue by TomVarga** [mwittig/edimax-smartplug#13]
As per https://github.com/mwittig/edimax-smartplug/blob/master/Downgrade.md using the fimrware update tool I should get the .bin files, but the tool does not seem to work regardless if I'm connected to the wifi of the plug or my routers.

Could you please provide me with the SP2101W_2.08_upg.bin file?

**Comment by mwittig** [comment]
No, I can't do that. 

I have double-checked the instructions and it still works as described! Please read the instructions carefully.
