### ISSUE TITLE
SP-2101W V2

### ISSUE THREAD

**Issue by pompfe** [mwittig/edimax-smartplug#14]
Is the SP-2101W V2 supported?  Did someone test against V2?
It seems to be impossible to buy "V1" anymore.
Thanks.

**Comment by mwittig** [comment]
The following thread contains hints about downgrade procedure. The most relevant posts can be found on page 6 and 15 as far as I can tell. Use at your own risk

https://www.photovoltaikforum.com/thread/125453-shm-2-0-und-edimax-sp-2101w-v2-mit-firmware-3-00c/

**Comment by mwittig** [comment]
I am closing this now as I have added a notice to the README. @pompfe If you have new findings or whish to follow-up on this please re-open.
